# -*- Makefile -*-
# Minimal P3T1755 I3C temp-sensor model for KM Simics

SIMICS_API := latest
THREAD_SAFE := yes

MODULE_CLASSES := p3t1755
MODULE_COMPONENTS := p3t1755_comp
SRC_FILES := p3t1755.dml
PYTHON_FILES := p3t1755_comp.py module_load.py board_hooks.py

include $(MODULE_MAKEFILE)
