# -*- Makefile -*-
# VSIP mem_source Simics module

SIMICS_API := latest
THREAD_SAFE := yes

MODULE_CLASSES := vsip_memsrc
MODULE_COMPONENTS := vsip_memsrc_comp
SRC_FILES := vsip_memsrc.dml
PYTHON_FILES := vsip_memsrc_comp.py module_load.py board_hooks.py

include $(MODULE_MAKEFILE)
